//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemHoTroTimKiemVietLam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TroGiupViecLamEntities : DbContext
    {
        public TroGiupViecLamEntities()
            : base("name=TroGiupViecLamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoanhNghiep> DoanhNghieps { get; set; }
        public virtual LyLichXinViec LyLichXinViecs { get; set; }
        public virtual DbSet<NganhNghe> NganhNghes { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
