//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemHoTroTimKiemVietLam
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichXinViec
    {
        public string maCV { get; set; }
        public string tenNV { get; set; }
        public string queQuan { get; set; }
        public string dcThuongTru { get; set; }
        public string dcTamTru { get; set; }
        public string soDT { get; set; }
        public string cmND { get; set; }
        public string sucKhoe { get; set; }
        public string eMail { get; set; }
        public string maDN { get; set; }
    
        public virtual DoanhNghiep DoanhNghiep { get; set; }
    }
}
